import Footer from '../../../Components/Layouts/Footer/Footer';
import Blogs from '../../../Components/Layouts/Blogs/Blogs';
import Navbar from '../../../Components/Stateful/Navbar/navbar';

export const metadata = {
  title: 'testing meta',
  description: 'Generated by create-nx-workspace',
};

const Blog_With_ID = ({ params }: { params: { id: string } }) => {
  return (
    <>
      <Navbar />
      <div>Blog with id : {params.id}</div>
      <Blogs />
      <Footer />
    </>
  );
};

export default Blog_With_ID;
