import Footer from '../../Components/Layouts/Footer/Footer';
import Blogs from '../../Components/Layouts/Blogs/Blogs';
import Navbar from '../../Components/Stateful/Navbar/navbar';
import Suggested_Blogs from '@/Components/Layouts/Latest_Blogs/Latest_Blogs';
import Section from '@/Components/Stateless/Section/Section';
import Team from '@/Components/Layouts/Team/Team';
import Make_Appointment from '@/Components/Layouts/Make_Appointment/Make_Appointment';

export const metadata = {
  title: 'testing meta',
  description: 'Generated by create-nx-workspace',
};

const ALL_BLOGS = () => {
  return (
    <>
      <Navbar />

      <Suggested_Blogs title="Latest Blogs" />

      {/* <Blogs />
       */}
      <Team />
      <Make_Appointment />
      <Footer />
    </>
  );
};

export default ALL_BLOGS;
