export const caseTypesPakistanObjects = [
  { value: 'Civil Cases', text: 'Civil Cases' },
  { value: 'Criminal Cases', text: 'Criminal Cases' },
  { value: 'Family Cases', text: 'Family Cases' },
  { value: 'Property Cases', text: 'Property Cases' },
  { value: 'Commercial Cases', text: 'Commercial Cases' },
  { value: 'Constitutional Cases', text: 'Constitutional Cases' },
  { value: 'Administrative Cases', text: 'Administrative Cases' },
  { value: 'Contractual Disputes', text: 'Contractual Disputes' },
  { value: 'Labor and Employment Cases', text: 'Labor and Employment Cases' },
  { value: 'Tax Cases', text: 'Tax Cases' },
  { value: 'Intellectual Property Cases', text: 'Intellectual Property Cases' },
  { value: 'Environmental Cases', text: 'Environmental Cases' },
  { value: 'Consumer Protection Cases', text: 'Consumer Protection Cases' },
  { value: 'Banking and Finance Cases', text: 'Banking and Finance Cases' },
  { value: 'Insurance Cases', text: 'Insurance Cases' },
  { value: 'Immigration Cases', text: 'Immigration Cases' },
  { value: 'Human Rights Cases', text: 'Human Rights Cases' },
  { value: 'Landlord-Tenant Disputes', text: 'Landlord-Tenant Disputes' },
  { value: 'Personal Injury Cases', text: 'Personal Injury Cases' },
  { value: 'Medical Malpractice Cases', text: 'Medical Malpractice Cases' },
  { value: 'Defamation Cases', text: 'Defamation Cases' },
  { value: 'Cybercrime Cases', text: 'Cybercrime Cases' },
  { value: 'Juvenile Cases', text: 'Juvenile Cases' },
  { value: 'Arbitration Cases', text: 'Arbitration Cases' },
  {
    value: 'International Trade Disputes',
    text: 'International Trade Disputes',
  },
];
