import Footer from '../../Components/Layouts/Footer/Footer';
import Blogs from '../../Components/Layouts/Blogs/Blogs';
import Navbar from '../../Components/Stateful/Navbar/navbar';

export const metadata = {
  title: 'testing meta',
  description: 'Generated by create-nx-workspace',
};

const ALL_BLOGS = () => {
  return (
    <>
      <Navbar />
      <div>Blogs</div>
      <Blogs />
      <Footer />
    </>
  );
};

export default ALL_BLOGS;
